---
spring:
    main:
        banner-mode: console
    groovy:
        template:
            check-template-location: false
    jackson:
        serialization:
            indent_output: true
        serialization-inclusion: non_null

management:
    context-path: /operations

# configure operations endpoints
endpoints:
  health:
    sensitive: false

server:
  port: 8080
  contextPath: /

# which logback configuration file to use
logging:
  config: classpath:logback.xml

# Override the default values of the info endpoint
info:
  app:
    name: ${name}
    description: ${description}
    version: ${version}

# Override the default security properties, defined in org.springframework.boot.autoconfigure.security.SecurityProperties
security:
  user:
    name: operations
    password: operations
  basic:
    enabled: false
    realm: dcr

# app specific properties
dcr:
  foo: default

#---------- profile specific overrides ----------#

---
spring:
  profiles: bamboo
dcr:
  foo: bamboo
