version: '2'
services:
    ${projectName}:
        image: "${dockerRegistry}/${dockerAccount}/${projectName}:${version}"
        labels:
            org.kurron.built-on: "${generated}"
            org.kurron.branch: "${branch}"
            org.kurron.version: "${version}"
        container_name: "${projectName}"
        network_mode: "host"
        environment:
            JVM_HEAP_MAX: 128m
            JVM_JMX_HOST: 127.0.0.1
            JVM_JMX_PORT: 2020
        cpu_shares: 0
        cpu_quota: 0
        mem_limit: 256m
        memswap_limit: 256m
        shm_size: 64M